FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend ./backend
COPY ./shared ./shared

# Не хардкодим ключ
# ENV OPENAI_API_KEY=your_dummy_key

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]